apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: s3
  name: ${Rand.RFC1123Subdomain}
spec:
  forProvider:
    objectLockEnabled: true
    region: eu-central-1
    tags:
      Name: SampleBucket