apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: aws-load-balancer-controller
    server: https://kubernetes.default.svc
  project: development
  source:
    path: k8s/apps/aws-load-balancer-controller
    repoURL: git@github.com:rafnow1403/14a-deploy-eks.git
    targetRevision: 007-crossplane-aws-infrastrucutre
    helm:
      releaseName: aws-load-balancer-controller
      valueFiles: 
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
