apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cka-exam
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cka-exam
    server: https://kubernetes.default.svc
  project: development
  source:
    path: k8s/apps/cka-exam
    repoURL: git@github.com:rafnow1403/14a-deploy-eks.git
    targetRevision: 007-crossplane-aws-infrastrucutre
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
