apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:stable
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 5;done"]
    # securityContext:
    #   capabilities:
    #     add:
    #       - "SYS_TIME"