argocd-apps:
  applications:
    - name: argocd
      namespace: argocd
      project: argocd
      source:
        repoURL: git@github.com:rafnow1403/14a-deploy-eks.git
        targetRevision: HEAD
        path: k8s/argocd
        helm:
          version: v3
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    - name: appofapps
      namespace: argocd
      project: argocd
      source:
        repoURL: git@github.com:rafnow1403/14a-deploy-eks.git
        targetRevision: HEAD
        path: k8s/appofapps/templates
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  projects:
    - name: argocd
      namespace: argocd
      description: ArgoCD project
      destinations:
        - namespace: argocd
          server: https://kubernetes.default.svc
      sourceRepos:
      - '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

    - name: development
      namespace: argocd
      description: Development project
      destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
      sourceRepos:
      - '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'