argocd-apps:

  applications:
    - name: argocd
      namespace: argocd
      project: argocd
      source:
        repoURL: git@github.com:rafnow1403/14a-deploy-eks.git
        tragetRevision: HEAD
        path: k8s/argocd
        helm:
          version: v3
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    - name: argocd-apps
      namespace: argocd
      project: argocd
      source:
        repoURL: git@github.com:rafnow1403/14a-deploy-eks.git
        tragetRevision: HEAD
        path: k8s/argocd-apps
        helm:
          version: v3
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd-apps
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  projects:
    - name: argocd
      namespace: argocd
      description: ArgoCD project
      destinations:
        - namespace: argocd
          server: https://kubernetes.default.svc
      sourceRepos:
      - '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      # orphanedResources:
      #   warn: false
    # - name: infra
    #   namespace: argocd-apps
    #   additionalLabels: {}
    #   additionalAnnotations: {}
    #   description: Infra Project
    #   sourceRepos:
    #   - '*'
    #   destinations:
    #   - namespace: argocd-apps
    #     server: https://kubernetes.default.svc
    #   clusterResourceWhitelist:
    #   - group: '*'
    #     kind: '*'
    #   orphanedResources:
    #     warn: false
    # - name: test-project
    #   namespace: argocd-apps