argo-cd:
  redis-ha:
    enabled: false
  controller:
    replicas: 1
  server:
    replicas: 1
  repoServer:
    replicas: 1
  applicationSet:
    replicas: 1
  configs:
    secret:
      argocdServerAdminPassword: $2a$10$Bk9SieceBmq4.dP/sQUfZ.RDArHqadJmgwzGYAZzhRVIOvNSEgjay
    
    # credentialTemplates:
    #   14a-deploy-eks:
    #     url: git@github.com:rafnow1403/14a-deploy-eks.git
    #     sshPrivateKey: |
    #       -----BEGIN OPENSSH PRIVATE KEY-----
    #       b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    #       NhAAAAAwEAAQAAAgEAxbv8PEWQZwu341GtO0V4ydpGTIW/iz/G+KBx1d6zya1wjjZq2JJA
    #       EVXiTs5NlzaSzIn+JhGwfDd4DRL79xupr0tkjsOeiOZ9jEHWY8su4NmMsD/mm2tY+jc3j+
    #       NoRkT9VQBXMAAAAbcmFmYWxub3dpY2tpQHJhZmFzLWFpci5ob21l
    #       -----END OPENSSH PRIVATE KEY-----
      
    # repositories:
    #   14a-deploy-eks:
    #     url: git@github.com:rafnow1403/14a-deploy-eks.git
    #     name: 14a-deploy-eks 
  
  # server:
  #   service:
  #     type: LoadBalancer


argocd-apps:

  applications:
    - name: argocd
      namespace: argocd
      project: argocd
      source:
        repoURL: git@github.com:rafnow1403/14a-deploy-eks.git
        targetRevision: HEAD
        path: k8s/argocd
        helm:
          version: v3
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  projects:
    - name: argocd
      namespace: argocd
      description: ArgoCD project
      destinations:
        - namespace: argocd
          server: https://kubernetes.default.svc
      sourceRepos:
      - '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'